2012/01/29 15:11:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /home/sagi/yii-119/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/sagi/yii-119/framework/db/CDbConnection.php(331): CDbConnection->open()
#1 /home/sagi/yii-119/framework/db/CDbConnection.php(309): CDbConnection->setActive(true)
#2 /home/sagi/yii-119/framework/base/CModule.php(388): CDbConnection->init()
#3 /home/sagi/yii-119/framework/base/CModule.php(104): CModule->getComponent('db')
#4 /home/sagi/yii-119/framework/gii/generators/model/ModelCode.php(54): CModule->__get('db')
#5 /home/sagi/yii-119/framework/web/CFormModel.php(40): ModelCode->init()
#6 /home/sagi/yii-119/framework/gii/CCodeGenerator.php(152): CFormModel->__construct()
#7 /home/sagi/yii-119/framework/gii/CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 /home/sagi/yii-119/framework/web/actions/CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 /home/sagi/yii-119/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /home/sagi/yii-119/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /home/sagi/yii-119/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/sagi/yii-119/framework/web/CWebApplication.php(276): CController->run('')
#13 /home/sagi/yii-119/framework/web/CWebApplication.php(135): CWebApplication->runController('gii/model')
#14 /home/sagi/yii-119/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/sagi/yii-demo/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/sagi/yii-demo/index.php/gii/model
HTTP_REFERER=http://localhost/sagi/yii-demo/index.php/gii/default/index
---
